"""Load the exported files into Snowflake.

Each table is PUT to an internal stage, COPY'd into a temporary table (casting JSON fields to column types),
then MERGEd into the real table on its key, so loading the same export twice is harmless. Future events
that disappeared from the latest export (cancelled, or merged into another event) are deleted.

Connection settings come from environment variables (see .env.example):
SNOWFLAKE_ACCOUNT, SNOWFLAKE_USER, and SNOWFLAKE_PASSWORD or SNOWFLAKE_PRIVATE_KEY_FILE or
SNOWFLAKE_AUTHENTICATOR=externalbrowser; optionally SNOWFLAKE_ROLE, SNOWFLAKE_WAREHOUSE,
SNOWFLAKE_DATABASE, SNOWFLAKE_SCHEMA.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path

from .schema import EXPORTED_TABLES, Table, full_snowflake_ddl, snowflake_select

log = logging.getLogger(__name__)

STAGE = "UMD_EVENTS_STAGE"


def _statements(sql: str) -> list[str]:
    lines = [line for line in sql.splitlines() if not line.strip().startswith("--")]
    return [s.strip() for s in "\n".join(lines).split(";") if s.strip()]


def merge_sql(table: Table, staging: str) -> str:
    cols = [c.upper() for c, _ in table.columns]
    keys = [k.upper() for k in table.key]
    on = " AND ".join(f"t.{k} = s.{k}" for k in keys)
    updates = ", ".join(f"{c} = s.{c}" for c in cols if c not in keys)
    dedupe = ", ".join(keys)
    return (
        f"MERGE INTO {table.name} t\n"
        f"USING (SELECT * FROM {staging} QUALIFY ROW_NUMBER() OVER (PARTITION BY {dedupe} ORDER BY {dedupe}) = 1) s\n"
        f"ON {on}\n"
        f"WHEN MATCHED THEN UPDATE SET {updates}\n"
        f"WHEN NOT MATCHED THEN INSERT ({', '.join(cols)}) VALUES ({', '.join('s.' + c for c in cols)})"
    )


def copy_sql(table: Table, staging: str, stage_path: str) -> str:
    return (
        f"COPY INTO {staging}\nFROM (\n    SELECT\n        {snowflake_select(table)}\n    FROM {stage_path}\n)\n"
        f"FILE_FORMAT = (TYPE = JSON) ON_ERROR = ABORT_STATEMENT"
    )


CLEANUP_SQL = [
    # Future events missing from the latest snapshot were cancelled upstream or merged into another event.
    # Guarded so an empty/missing EVENTS upload never wipes the table.
    "DELETE FROM EVENTS WHERE start_time >= CURRENT_TIMESTAMP() "
    "AND event_id NOT IN (SELECT event_id FROM EVENTS_STAGING) AND EXISTS (SELECT 1 FROM EVENTS_STAGING)",
    "DELETE FROM EVENT_SOURCES WHERE canonical_event_id NOT IN (SELECT event_id FROM EVENTS) "
    "AND EXISTS (SELECT 1 FROM EVENTS_STAGING)",
]


def manual_load_sql() -> str:
    """The same load as SQL, for running in a Snowsight worksheet after uploading the .jsonl files to the
    stage by hand (Data > Databases > stage > + Files)."""
    out = [
        "-- Generated by `umd-events snowflake-sql`. Run after snowflake_schema.sql.",
        "-- 1. Create the stage, then upload every data/exports/<TABLE>.jsonl into a folder named after its table:",
        "--    @UMD_EVENTS_STAGE/EVENTS/EVENTS.jsonl, @UMD_EVENTS_STAGE/VENUES/VENUES.jsonl, ...",
        f"CREATE STAGE IF NOT EXISTS {STAGE} FILE_FORMAT = (TYPE = JSON);",
        "",
        "-- 2. Load each table (COPY into a temp table, then MERGE on the key).",
    ]
    for table in EXPORTED_TABLES:
        staging = f"{table.name}_STAGING"
        out += [
            f"\n-- {table.name}",
            f"CREATE OR REPLACE TEMPORARY TABLE {staging} LIKE {table.name};",
            copy_sql(table, staging, f"@{STAGE}/{table.name}/") + ";",
            merge_sql(table, staging) + ";",
        ]
    out += ["\n-- 3. Remove future events that are no longer listed."] + [s + ";" for s in CLEANUP_SQL]
    return "\n".join(out) + "\n"


def write_sql_files(sql_dir: Path) -> None:
    sql_dir.mkdir(parents=True, exist_ok=True)
    (sql_dir / "snowflake_schema.sql").write_text(full_snowflake_ddl(), encoding="utf-8")
    (sql_dir / "snowflake_load.sql").write_text(manual_load_sql(), encoding="utf-8")


def connect():
    try:
        import snowflake.connector
    except ImportError as exc:
        raise RuntimeError("snowflake-connector-python is not installed: run `uv sync --extra snowflake`") from exc

    env = lambda name: os.getenv(name) or None  # noqa: E731
    missing = [n for n in ("SNOWFLAKE_ACCOUNT", "SNOWFLAKE_USER") if not env(n)]
    if missing:
        raise RuntimeError(f"missing Snowflake settings: {', '.join(missing)} (see .env.example)")
    params = {
        "account": env("SNOWFLAKE_ACCOUNT"),
        "user": env("SNOWFLAKE_USER"),
        "role": env("SNOWFLAKE_ROLE"),
        "warehouse": env("SNOWFLAKE_WAREHOUSE"),
        "database": env("SNOWFLAKE_DATABASE"),
        "schema": env("SNOWFLAKE_SCHEMA"),
        "application": "umd-events",
    }
    if env("SNOWFLAKE_PRIVATE_KEY_FILE"):
        params["private_key_file"] = env("SNOWFLAKE_PRIVATE_KEY_FILE")
        if env("SNOWFLAKE_PRIVATE_KEY_PASSPHRASE"):
            params["private_key_file_pwd"] = env("SNOWFLAKE_PRIVATE_KEY_PASSPHRASE")
    elif env("SNOWFLAKE_PASSWORD"):
        params["password"] = env("SNOWFLAKE_PASSWORD")
    else:
        params["authenticator"] = env("SNOWFLAKE_AUTHENTICATOR") or "externalbrowser"
    return snowflake.connector.connect(**{k: v for k, v in params.items() if v})


def load(export_dir: Path) -> dict[str, int]:
    """Create tables/views if needed and merge every exported table into Snowflake."""
    loaded: dict[str, int] = {}
    con = connect()
    try:
        cur = con.cursor()
        database, schema = os.getenv("SNOWFLAKE_DATABASE"), os.getenv("SNOWFLAKE_SCHEMA")
        if database and schema:
            cur.execute(f"CREATE SCHEMA IF NOT EXISTS {database}.{schema}")
            cur.execute(f"USE SCHEMA {database}.{schema}")
        for statement in _statements(full_snowflake_ddl()):
            cur.execute(statement)
        cur.execute(f"CREATE STAGE IF NOT EXISTS {STAGE} FILE_FORMAT = (TYPE = JSON)")

        for table in EXPORTED_TABLES:
            path = export_dir / f"{table.name}.jsonl"
            if not path.exists() or path.stat().st_size == 0:
                log.info("snowflake: %s has no rows, skipped", table.name)
                continue
            staging = f"{table.name}_STAGING"
            stage_path = f"@{STAGE}/{table.name}/"
            cur.execute(f"REMOVE {stage_path}")
            cur.execute(f"PUT 'file://{path.resolve().as_posix()}' {stage_path} AUTO_COMPRESS = TRUE OVERWRITE = TRUE")
            cur.execute(f"CREATE OR REPLACE TEMPORARY TABLE {staging} LIKE {table.name}")
            cur.execute(copy_sql(table, staging, stage_path))
            cur.execute(f"SELECT COUNT(*) FROM {staging}")
            loaded[table.name] = cur.fetchone()[0]
            cur.execute(merge_sql(table, staging))
            log.info("snowflake: merged %d rows into %s", loaded[table.name], table.name)

        if "EVENTS" in loaded:
            for statement in CLEANUP_SQL:
                cur.execute(statement)
    finally:
        con.close()
    return loaded
