USE DATABASE LIFEDATA;
USE SCHEMA MAIN;

-- New procedure so the API can load the logged-in user by ID (never returns the password hash)
CREATE OR REPLACE PROCEDURE LIFEDATA.MAIN.GET_USER_BY_ID(P_USER_ID INTEGER)
RETURNS TABLE (
    USER_ID INTEGER,
    NAME VARCHAR,
    EMAIL VARCHAR,
    USERNAME VARCHAR
)
LANGUAGE SQL
AS
$$
DECLARE
    RES RESULTSET;
BEGIN
    RES := (
        SELECT USER_ID, NAME, EMAIL, USERNAME
        FROM LIFEDATA.MAIN.USERS
        WHERE USER_ID = :P_USER_ID
    );
    RETURN TABLE(RES);
END;
$$;

-- Least-privilege role for the API: it can CALL procedures but cannot touch tables directly.
-- Procedures run with owner's rights by default, so this is enough.
CREATE ROLE IF NOT EXISTS LIFEDATA_API_ROLE;

GRANT USAGE ON DATABASE LIFEDATA TO ROLE LIFEDATA_API_ROLE;
GRANT USAGE ON SCHEMA LIFEDATA.MAIN TO ROLE LIFEDATA_API_ROLE;

GRANT USAGE ON PROCEDURE LIFEDATA.MAIN.CREATE_USER(VARCHAR, VARCHAR, VARCHAR, VARCHAR) TO ROLE LIFEDATA_API_ROLE;
GRANT USAGE ON PROCEDURE LIFEDATA.MAIN.CREATE_PROFILE(INTEGER, VARCHAR, VARCHAR, VARCHAR) TO ROLE LIFEDATA_API_ROLE;
GRANT USAGE ON PROCEDURE LIFEDATA.MAIN.GET_USER(VARCHAR) TO ROLE LIFEDATA_API_ROLE;
GRANT USAGE ON PROCEDURE LIFEDATA.MAIN.GET_USER_BY_ID(INTEGER) TO ROLE LIFEDATA_API_ROLE;
GRANT USAGE ON PROCEDURE LIFEDATA.MAIN.GET_PROFILE(INTEGER) TO ROLE LIFEDATA_API_ROLE;

-- Replace MY_WH with your warehouse name
GRANT USAGE ON WAREHOUSE MY_WH TO ROLE LIFEDATA_API_ROLE;

-- Service user for the API (use key-pair auth in production)
-- CREATE USER LIFEDATA_API_SVC PASSWORD = '...' DEFAULT_ROLE = LIFEDATA_API_ROLE;
-- GRANT ROLE LIFEDATA_API_ROLE TO USER LIFEDATA_API_SVC;
