-- CREATE ROLE PROJECT_DEVELOPER;
GRANT USAGE ON DATABASE LIFEDATA
TO ROLE PROJECT_DEVELOPER;

GRANT USAGE ON SCHEMA LIFEDATA.MAIN
TO ROLE PROJECT_DEVELOPER;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA LIFEDATA.MAIN
TO ROLE PROJECT_DEVELOPER;

CREATE USER Aayush
    PASSWORD = '2012';

GRANT ROLE PROJECT_DEVELOPER TO USER Aayush;

CREATE USER Turbolb
    PASSWORD = '2013';

GRANT ROLE PROJECT_DEVELOPER TO USER Turbolb;

CREATE USER Kerry
    PASSWORD = '2014';

GRANT ROLE PROJECT_DEVELOPER TO USER Kerry;

//USE URL: ZSHIALB-PJ28209.snowflakecomputing.com
    