-- Run this entire file in Snowsight with a role authorized to create these objects.
-- Additive setup: no existing database or table is replaced.
CREATE DATABASE IF NOT EXISTS LIFEDATA;
CREATE SCHEMA IF NOT EXISTS LIFEDATA.LIFEDATA;

CREATE TABLE IF NOT EXISTS LIFEDATA.LIFEDATA.USERS (
  USER_ID INTEGER AUTOINCREMENT PRIMARY KEY,
  NAME VARCHAR, EMAIL VARCHAR, USERNAME VARCHAR,
  PASSWORD VARCHAR
);
-- PASSWORD mirrors the supplied schema only. This integration never reads/writes it.
-- Implement account authentication with a proper auth provider before public deployment.
CREATE TABLE IF NOT EXISTS LIFEDATA.LIFEDATA.PROFILES (
  PROFILE_ID INTEGER AUTOINCREMENT PRIMARY KEY,
  USER_ID INTEGER UNIQUE, NAME VARCHAR, MAJOR VARCHAR, BIO VARCHAR,
  FOREIGN KEY (USER_ID) REFERENCES LIFEDATA.LIFEDATA.USERS(USER_ID)
);
CREATE TABLE IF NOT EXISTS LIFEDATA.LIFEDATA.GROUPS (
  GROUP_ID INTEGER AUTOINCREMENT PRIMARY KEY, GROUP_NAME VARCHAR
);
CREATE TABLE IF NOT EXISTS LIFEDATA.LIFEDATA.EVENT_SOURCES (
  SOURCE_ID INTEGER AUTOINCREMENT PRIMARY KEY,
  SOURCE_NAME VARCHAR, SOURCE_URL VARCHAR, SOURCE_TYPE VARCHAR
);
CREATE TABLE IF NOT EXISTS LIFEDATA.LIFEDATA.EVENTS (
  EVENT_ID INTEGER AUTOINCREMENT PRIMARY KEY,
  EVENT_TITLE VARCHAR, EVENT_DESCRIPTION VARCHAR, SOURCE_ID INTEGER,
  FOREIGN KEY (SOURCE_ID) REFERENCES LIFEDATA.LIFEDATA.EVENT_SOURCES(SOURCE_ID)
);
CREATE TABLE IF NOT EXISTS LIFEDATA.LIFEDATA.TAGS (
  TAG_ID INTEGER AUTOINCREMENT PRIMARY KEY, TAG_NAME VARCHAR UNIQUE
);
CREATE TABLE IF NOT EXISTS LIFEDATA.LIFEDATA.PROFILE_TAGS (
  PROFILE_ID INTEGER, TAG_ID INTEGER, PRIMARY KEY (PROFILE_ID, TAG_ID),
  FOREIGN KEY (PROFILE_ID) REFERENCES LIFEDATA.LIFEDATA.PROFILES(PROFILE_ID),
  FOREIGN KEY (TAG_ID) REFERENCES LIFEDATA.LIFEDATA.TAGS(TAG_ID)
);
CREATE TABLE IF NOT EXISTS LIFEDATA.LIFEDATA.GROUP_TAGS (
  GROUP_ID INTEGER, TAG_ID INTEGER, PRIMARY KEY (GROUP_ID, TAG_ID),
  FOREIGN KEY (GROUP_ID) REFERENCES LIFEDATA.LIFEDATA.GROUPS(GROUP_ID),
  FOREIGN KEY (TAG_ID) REFERENCES LIFEDATA.LIFEDATA.TAGS(TAG_ID)
);
CREATE TABLE IF NOT EXISTS LIFEDATA.LIFEDATA.EVENT_TAGS (
  EVENT_ID INTEGER, TAG_ID INTEGER, PRIMARY KEY (EVENT_ID, TAG_ID),
  FOREIGN KEY (EVENT_ID) REFERENCES LIFEDATA.LIFEDATA.EVENTS(EVENT_ID),
  FOREIGN KEY (TAG_ID) REFERENCES LIFEDATA.LIFEDATA.TAGS(TAG_ID)
);
-- The supplied schema omitted these fields required for useful discovery cards.
ALTER TABLE LIFEDATA.LIFEDATA.GROUPS ADD COLUMN IF NOT EXISTS GROUP_DESCRIPTION VARCHAR DEFAULT '';
ALTER TABLE LIFEDATA.LIFEDATA.GROUPS ADD COLUMN IF NOT EXISTS LOCATION VARCHAR DEFAULT '';
ALTER TABLE LIFEDATA.LIFEDATA.GROUPS ADD COLUMN IF NOT EXISTS MEETING_DETAILS VARCHAR DEFAULT '';
ALTER TABLE LIFEDATA.LIFEDATA.GROUPS ADD COLUMN IF NOT EXISTS CAMPUS VARCHAR DEFAULT 'UMD';
ALTER TABLE LIFEDATA.LIFEDATA.GROUPS ADD COLUMN IF NOT EXISTS IS_ACTIVE NUMBER(1,0) DEFAULT 1;
ALTER TABLE LIFEDATA.LIFEDATA.GROUPS ADD COLUMN IF NOT EXISTS IS_DEMO BOOLEAN DEFAULT FALSE;
ALTER TABLE LIFEDATA.LIFEDATA.GROUPS ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP_TZ;
ALTER TABLE LIFEDATA.LIFEDATA.EVENTS ADD COLUMN IF NOT EXISTS LOCATION VARCHAR DEFAULT '';
ALTER TABLE LIFEDATA.LIFEDATA.EVENTS ADD COLUMN IF NOT EXISTS STARTS_AT TIMESTAMP_TZ;
ALTER TABLE LIFEDATA.LIFEDATA.EVENTS ADD COLUMN IF NOT EXISTS CAMPUS VARCHAR DEFAULT 'UMD';
ALTER TABLE LIFEDATA.LIFEDATA.EVENTS ADD COLUMN IF NOT EXISTS IS_ACTIVE NUMBER(1,0) DEFAULT 1;
ALTER TABLE LIFEDATA.LIFEDATA.EVENTS ADD COLUMN IF NOT EXISTS IS_DEMO BOOLEAN DEFAULT FALSE;
ALTER TABLE LIFEDATA.LIFEDATA.EVENTS ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP_TZ;

SHOW TABLES IN SCHEMA LIFEDATA.LIFEDATA;
