-- A unified catalog over the team's normalized schema.
CREATE OR REPLACE VIEW LIFEDATA.LIFEDATA.DISCOVERY_CATALOG AS
WITH ET AS (
  SELECT et.EVENT_ID, LISTAGG(DISTINCT t.TAG_NAME, ', ') WITHIN GROUP (ORDER BY t.TAG_NAME) AS TAGS
  FROM LIFEDATA.LIFEDATA.EVENT_TAGS et JOIN LIFEDATA.LIFEDATA.TAGS t ON t.TAG_ID = et.TAG_ID
  GROUP BY et.EVENT_ID
), GT AS (
  SELECT gt.GROUP_ID, LISTAGG(DISTINCT t.TAG_NAME, ', ') WITHIN GROUP (ORDER BY t.TAG_NAME) AS TAGS
  FROM LIFEDATA.LIFEDATA.GROUP_TAGS gt JOIN LIFEDATA.LIFEDATA.TAGS t ON t.TAG_ID = gt.TAG_ID
  GROUP BY gt.GROUP_ID
)
SELECT 'event:' || e.EVENT_ID::VARCHAR AS ITEM_ID, 'event' AS ITEM_TYPE,
  COALESCE(e.EVENT_TITLE, '') AS TITLE, COALESCE(e.EVENT_DESCRIPTION, '') AS DESCRIPTION,
  COALESCE(et.TAGS, '') AS TAGS, e.CAMPUS, e.STARTS_AT, e.IS_ACTIVE,
  COALESCE(e.LOCATION, '') AS LOCATION, '' AS MEETING_DETAILS, e.IS_DEMO, e.CREATED_AT,
  COALESCE(e.EVENT_TITLE, '') || ' | ' || COALESCE(e.EVENT_DESCRIPTION, '') || ' | ' || COALESCE(et.TAGS, '') AS SEARCH_TEXT
FROM LIFEDATA.LIFEDATA.EVENTS e LEFT JOIN ET ON et.EVENT_ID = e.EVENT_ID
UNION ALL
SELECT 'group:' || g.GROUP_ID::VARCHAR, 'group',
  COALESCE(g.GROUP_NAME, ''), COALESCE(g.GROUP_DESCRIPTION, ''), COALESCE(gt.TAGS, ''),
  g.CAMPUS, NULL::TIMESTAMP_TZ, g.IS_ACTIVE, COALESCE(g.LOCATION, ''), COALESCE(g.MEETING_DETAILS, ''), g.IS_DEMO, g.CREATED_AT,
  COALESCE(g.GROUP_NAME, '') || ' | ' || COALESCE(g.GROUP_DESCRIPTION, '') || ' | ' || COALESCE(gt.TAGS, '')
FROM LIFEDATA.LIFEDATA.GROUPS g LEFT JOIN GT ON gt.GROUP_ID = g.GROUP_ID;

-- FULL handles aggregation/joins in this small hackathon catalog.
-- Keep this source small. A materialized catalog is preferable at larger scale.
CREATE CORTEX SEARCH SERVICE IF NOT EXISTS LIFEDATA.LIFEDATA.TERPLINK_SEARCH
ON SEARCH_TEXT
ATTRIBUTES ITEM_ID, ITEM_TYPE, CAMPUS, STARTS_AT, IS_ACTIVE
WAREHOUSE = COMPUTE_WH
TARGET_LAG = '5 minutes'
REFRESH_MODE = FULL
AS SELECT * FROM LIFEDATA.LIFEDATA.DISCOVERY_CATALOG;
