-- Run once as ACCOUNTADMIN. Grants catalog-search access only.
CREATE ROLE IF NOT EXISTS TERPLINK_SEARCH_APP;
GRANT USAGE ON DATABASE LIFEDATA TO ROLE TERPLINK_SEARCH_APP;
GRANT USAGE ON SCHEMA LIFEDATA.LIFEDATA TO ROLE TERPLINK_SEARCH_APP;
GRANT USAGE ON CORTEX SEARCH SERVICE LIFEDATA.LIFEDATA.TERPLINK_SEARCH TO ROLE TERPLINK_SEARCH_APP;
GRANT ROLE TERPLINK_SEARCH_APP TO USER ASINGH81;
