-- Run after files 01-05. Additive live-backend migration.
ALTER TABLE LIFEDATA.LIFEDATA.USERS ADD COLUMN IF NOT EXISTS APP_USER_KEY VARCHAR;
ALTER TABLE LIFEDATA.LIFEDATA.PROFILES ADD COLUMN IF NOT EXISTS AVAILABILITY VARCHAR DEFAULT '';
ALTER TABLE LIFEDATA.LIFEDATA.EVENTS ADD COLUMN IF NOT EXISTS APP_ITEM_KEY VARCHAR;
ALTER TABLE LIFEDATA.LIFEDATA.EVENTS ADD COLUMN IF NOT EXISTS CREATED_BY_USER_ID INTEGER;
ALTER TABLE LIFEDATA.LIFEDATA.GROUPS ADD COLUMN IF NOT EXISTS APP_ITEM_KEY VARCHAR;
ALTER TABLE LIFEDATA.LIFEDATA.GROUPS ADD COLUMN IF NOT EXISTS CREATED_BY_USER_ID INTEGER;
CREATE TABLE IF NOT EXISTS LIFEDATA.LIFEDATA.SWIPES (
  USER_ID INTEGER NOT NULL,
  ITEM_ID VARCHAR NOT NULL,
  ACTION VARCHAR NOT NULL,
  SWIPED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (USER_ID,ITEM_ID),
  FOREIGN KEY (USER_ID) REFERENCES LIFEDATA.LIFEDATA.USERS(USER_ID)
);

CREATE OR REPLACE VIEW LIFEDATA.LIFEDATA.USER_IDENTITIES AS
SELECT USER_ID, APP_USER_KEY FROM LIFEDATA.LIFEDATA.USERS;

-- A separate application role; the existing read-only search token is unchanged.
CREATE ROLE IF NOT EXISTS TERPLINK_DATA_APP;
GRANT USAGE ON DATABASE LIFEDATA TO ROLE TERPLINK_DATA_APP;
GRANT USAGE ON SCHEMA LIFEDATA.LIFEDATA TO ROLE TERPLINK_DATA_APP;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TERPLINK_DATA_APP;
GRANT INSERT ON TABLE LIFEDATA.LIFEDATA.USERS TO ROLE TERPLINK_DATA_APP;
GRANT SELECT, INSERT, UPDATE ON TABLE LIFEDATA.LIFEDATA.PROFILES TO ROLE TERPLINK_DATA_APP;
GRANT SELECT, INSERT ON TABLE LIFEDATA.LIFEDATA.EVENTS TO ROLE TERPLINK_DATA_APP;
GRANT SELECT, INSERT ON TABLE LIFEDATA.LIFEDATA.GROUPS TO ROLE TERPLINK_DATA_APP;
GRANT SELECT, INSERT ON TABLE LIFEDATA.LIFEDATA.TAGS TO ROLE TERPLINK_DATA_APP;
GRANT SELECT, INSERT, DELETE ON TABLE LIFEDATA.LIFEDATA.PROFILE_TAGS TO ROLE TERPLINK_DATA_APP;
GRANT SELECT, INSERT, DELETE ON TABLE LIFEDATA.LIFEDATA.EVENT_TAGS TO ROLE TERPLINK_DATA_APP;
GRANT SELECT, INSERT, DELETE ON TABLE LIFEDATA.LIFEDATA.GROUP_TAGS TO ROLE TERPLINK_DATA_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE LIFEDATA.LIFEDATA.SWIPES TO ROLE TERPLINK_DATA_APP;
GRANT SELECT ON VIEW LIFEDATA.LIFEDATA.USER_IDENTITIES TO ROLE TERPLINK_DATA_APP;
GRANT SELECT ON VIEW LIFEDATA.LIFEDATA.DISCOVERY_CATALOG TO ROLE TERPLINK_DATA_APP;
GRANT ROLE TERPLINK_DATA_APP TO USER ASINGH81;
